name: Spring Boot CI

on:
  pull_request:
    paths:
      - "server/**"

jobs:
  build_server:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Build with Maven
        working-directory: ./server
        run: mvn --batch-mode --update-snapshots package
