name: React CI

on:
  pull_request:
    paths:
      - "webapp/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 18.16.x
        uses: actions/setup-node@v2
        with:
          node-version: "18.16.x"

      - name: Install Dependencies
        working-directory: ./webapp
        run: npm install

      - name: Test
        working-directory: ./webapp
        run: npm test

      - name: Build
        working-directory: ./webapp
        run: npm run build
